import { ROLES } from "@/constants/roles";
import { PERMISSIONS } from "@/constants/permissions";

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
  [ROLES.PENTESTER]: [
    PERMISSIONS.PENTEST_DASHBOARD_READ,
    PERMISSIONS.VULNERABILITIES_READ,
    PERMISSIONS.VULNERABILITIES_CREATE,
    PERMISSIONS.VULNERABILITIES_UPDATE,
    PERMISSIONS.REPORTS_EXPORT,
  ],
  [ROLES.DEVOPS]: [
    PERMISSIONS.DEVOPS_DASHBOARD_READ,
    PERMISSIONS.DEPLOYMENTS_READ,
    PERMISSIONS.DEPLOYMENTS_CREATE,
    PERMISSIONS.SERVERS_READ,
  ],
  [ROLES.REPRESENTATIVE]: [
    PERMISSIONS.REPRESENTATIVE_DASHBOARD_READ,
    PERMISSIONS.TICKETS_READ,
    PERMISSIONS.TICKETS_CREATE,
    PERMISSIONS.TICKETS_UPDATE,
  ],
  [ROLES.QA]: [
    PERMISSIONS.QA_DASHBOARD_READ,
    PERMISSIONS.QA_TEST_CASES_READ,
    PERMISSIONS.QA_TEST_CASES_CREATE,
    PERMISSIONS.QA_TEST_CASES_UPDATE,
    PERMISSIONS.VULNERABILITIES_READ,
  ],
};

export function getPermissionsFromRoles(roles = []) {
  return Array.from(new Set(roles.flatMap((role) => ROLE_PERMISSIONS[role] || [])));
}
