import { ROLES } from "@/constants/roles";
import { PERMISSIONS } from "@/constants/permissions";

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
  [ROLES.PENTESTER]: [
    PERMISSIONS.PENTEST_DASHBOARD_READ,
    PERMISSIONS.VULNERABILITIES_READ,
    PERMISSIONS.VULNERABILITIES_CREATE,
    PERMISSIONS.VULNERABILITIES_UPDATE,
    PERMISSIONS.REPORTS_EXPORT,
  ],
  [ROLES.SECURITY_PROJECT_MANAGER]: [
    PERMISSIONS.SECURITY_MANAGER_DASHBOARD_READ,
    PERMISSIONS.SECURITY_PROJECTS_READ,
    PERMISSIONS.SECURITY_PROJECTS_ASSIGN,
    PERMISSIONS.SECURITY_PROJECTS_ASSIGN_SELF,
    PERMISSIONS.SECURITY_FINDINGS_REVIEW,
    PERMISSIONS.SECURITY_FINDINGS_APPROVE,
    PERMISSIONS.SECURITY_FINDINGS_REJECT,
    PERMISSIONS.SECURITY_REPORTS_CREATE,
    PERMISSIONS.SECURITY_REPORTS_SUBMIT_FOR_APPROVAL,
    PERMISSIONS.PENTEST_DASHBOARD_READ,
    PERMISSIONS.VULNERABILITIES_READ,
    PERMISSIONS.VULNERABILITIES_CREATE,
    PERMISSIONS.VULNERABILITIES_UPDATE,
  ],
  [ROLES.DEVOPS]: [
    PERMISSIONS.DEVOPS_DASHBOARD_READ,
    PERMISSIONS.DEPLOYMENTS_READ,
    PERMISSIONS.DEPLOYMENTS_CREATE,
    PERMISSIONS.SERVERS_READ,
  ],
  [ROLES.REPRESENTATIVE]: [
    PERMISSIONS.REPRESENTATIVE_DASHBOARD_READ,
    PERMISSIONS.TICKETS_READ,
    PERMISSIONS.TICKETS_CREATE,
    PERMISSIONS.TICKETS_UPDATE,
  ],
  [ROLES.QA]: [
    PERMISSIONS.QA_DASHBOARD_READ,
    PERMISSIONS.QA_TEST_CASES_READ,
    PERMISSIONS.QA_TEST_CASES_CREATE,
    PERMISSIONS.QA_TEST_CASES_UPDATE,
    PERMISSIONS.VULNERABILITIES_READ,
  ],
  [ROLES.QUALITY_PROJECT_MANAGER]: [
    PERMISSIONS.QUALITY_MANAGER_DASHBOARD_READ,
    PERMISSIONS.QUALITY_PROJECTS_READ,
    PERMISSIONS.QUALITY_PROJECTS_ASSIGN,
    PERMISSIONS.QUALITY_PROJECTS_ASSIGN_SELF,
    PERMISSIONS.QUALITY_RESULTS_REVIEW,
    PERMISSIONS.QUALITY_RESULTS_APPROVE,
    PERMISSIONS.QUALITY_RESULTS_REJECT,
    PERMISSIONS.QUALITY_REPORTS_CREATE,
    PERMISSIONS.QUALITY_REPORTS_SUBMIT_FOR_APPROVAL,
    PERMISSIONS.QA_DASHBOARD_READ,
    PERMISSIONS.QA_TEST_CASES_READ,
    PERMISSIONS.QA_TEST_CASES_CREATE,
    PERMISSIONS.QA_TEST_CASES_UPDATE,
    PERMISSIONS.VULNERABILITIES_READ,
  ],
};

export function getPermissionsFromRoles(roles = []) {
  return Array.from(new Set(roles.flatMap((role) => ROLE_PERMISSIONS[role] || [])));
}
